v1170 (#28)

diff --git a/.github/workflows/x86_64-linux.yml b/.github/workflows/x86_64-linux.yml
--- a/.github/workflows/x86_64-linux.yml
+++ b/.github/workflows/x86_64-linux.yml
@@ -1,4 +1,4 @@
-name: Windows Only Integration
+name: x86_64-linux
 
 on:
   workflow_dispatch:
@@ -9,7 +9,7 @@ jobs:
     name: ${{ matrix.name }}
 
     env:
-      MAKEJOBS: "-j3"
+      MAKEJOBS: "-j20"
       CHECK_DOC: "0"
       CCACHE_SIZE: "100M"
       CCACHE_TEMPDIR: /tmp/.ccache-temp
@@ -17,43 +17,41 @@ jobs:
       PYTHON_DEBUG: "1"
       WINEDEBUG: fixme-all
       SDK_URL: https://bitcoincore.org/depends-sources/sdks
-      VERSION: "1.1.7.0"
+      VERSION: "1.1.7"
+      RELEASE_NAME: "$GITHUB_WORKFLOW"
+      RELEASE_TAG: "1.1.7"
 
     strategy:
       fail-fast: false
       matrix:
         name:
-          - x86_64-win
+          - x86_64-linux
 
         include:
-
-          - name: x86_64-win
-            host: x86_64-w64-mingw32
-            arch: "i386"
+          - name: x86_64-linux
+            host: x86_64-unknown-linux-gnu
             os: ubuntu-20.04
-            packages: python3 nsis g++-mingw-w64-x86-64 wine64 bc wine-binfmt
-            postinstall: |
-              sudo update-alternatives --set x86_64-w64-mingw32-gcc  /usr/bin/x86_64-w64-mingw32-gcc-posix
-              sudo update-alternatives --set x86_64-w64-mingw32-g++  /usr/bin/x86_64-w64-mingw32-g++-posix
-              sudo update-binfmts --import /usr/share/binfmts/wine
+            packages: bc python3-zmq
             run-tests: false
             dep-opts: ""
-            config-opts: "--disable-shared --enable-gui=qt5"
+            config-opts: "--enable-gui=qt5 --enable-zmq --enable-glibc-back-compat --enable-reduce-exports"
             goal: install
-            strip-cmd: "x86_64-w64-mingw32-strip"
+            strip-cmd: "strip"
 
-    runs-on: ${{ matrix.os }}
+    runs-on: self-hosted
 
     steps:
       - name: Add architecture
         if: ${{ matrix.arch }}
         run: |
           sudo dpkg --add-architecture "${{ matrix.arch }}"
+  
       - name: Install packages
         run: |
           sudo apt-get update
           sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl ca-certificates ccache python3 rsync git procps bison
           sudo apt-get install ${{ matrix.packages }}
+
       - name: Post install
         if: ${{ matrix.postinstall }}
         run: ${{ matrix.postinstall }}
@@ -61,15 +59,13 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-
       - name: Cache SDK
         uses: actions/cache@v4
         with:
           path: depends/sdk-sources
           key: sdk-${{ runner.os }}-${{ matrix.name }}
           restore-keys: sdk-${{ runner.os }}-
-          #if: matrix.sdk
-
+          save-always: true
 
       - name: Install SDK
         if: ${{ matrix.sdk }}
@@ -78,18 +74,19 @@ jobs:
           mkdir -p depends/SDKs
           curl --location --fail $SDK_URL/MacOSX${{ matrix.sdk }}.sdk.tar.gz -o depends/sdk-sources/MacOSX${{ matrix.sdk }}.sdk.tar.gz
           tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${{ matrix.sdk }}.sdk.tar.gz
+
       - name: Cache Dependencies
         uses: actions/cache@v4
         with:
           path: depends/built
           key: dependencies-${{ runner.os }}-${{ matrix.name }}-${{ hashFiles('depends/packages/*') }}
           restore-keys: dependencies-${{ runner.os }}-${{ matrix.name }}-
-          #if: steps.Build Depends.outputs.cache-hit != 'true'
+          save-always: true
 
       - name: Build depends
         id: Build_Depends
         run: |
-          make $MAKEJOBS -C depends HOST=${{ matrix.host }} ${{ matrix.dep-opts }}
+          make -C depends HOST=${{ matrix.host }} ${{ env.MAKEJOBS }} ${{ matrix.dep-opts }}
         continue-on-error: true
       
       - name: CCache
@@ -98,15 +95,13 @@ jobs:
           path: ~/.ccache
           key: ccache-${{ runner.os }}-${{ matrix.name }}-${{ hashFiles('**/configure.ac') }}
           restore-keys: ccache-${{ runner.os }}-${{ matrix.name }}-
-          #if: steps.Build Depends.outputs.cache-hit != 'true'
-
 
       - name: Build Pulsar Core
         run: |
-          #depends/${{ matrix.host }}/native/bin/ccache --max-size=$CCACHE_SIZE
           ./autogen.sh
           ./configure --prefix=`pwd`/depends/${{ matrix.host }} ${{ matrix.config-opts }} || ( cat config.log && false)
-          make $MAKEJOBS ${{ matrix.goal }} || ( echo "Build failure. Verbose build follows." && make ${{ matrix.goal }} V=1 ; false )
+          make ${{ env.MAKEJOBS }} ${{ matrix.goal }} || ( echo "Build failure. Verbose build follows." && make ${{ matrix.goal }} V=1 ; false )
+
           
       - name: Strip built binaries
         run: |
@@ -121,42 +116,37 @@ jobs:
           cp src/pulsar-tx* release/
         continue-on-error: true
       
-      - name: Chmod
-        if: |
-          matrix.name != 'x86_64-macos' &&
-          matrix.name != 'x86_64-win'
+      - name: Chmod & Tar
         run: |
           chmod -R +x release/
-          
-      - name: Tar files
-        if: |
-          matrix.name != 'x86_64-macos' &&
-          matrix.name != 'x86_64-win'
-        run: |
-            tar -cvf Pulsar-${{ env.VERSION }}-${{ matrix.name }}.tar -C release/ .
-      
+          tar -cvf Pulsar-${{ env.VERSION }}-${{ matrix.name }}.tar -C release/ .
+
       - name: Upload artifacts
-        if: |
-          matrix.name != 'x86_64-macos' &&
-          matrix.name != 'x86_64-win'
         uses: actions/upload-artifact@v4
         with:
           name: Pulsar-${{ env.VERSION }}-${{ matrix.name }}
           path: |
-            Pulsar-${{ env.VERSION }}-${{ matrix.name }}.tar
-            
-      - name: Upload artifacts WIN/OSX
-        if: |
-          matrix.name == 'x86_64-macos' ||
-          matrix.name == 'x86_64-win'
-        uses: actions/upload-artifact@v4
+            Pulsar-${{ env.VERSION }}-${{ matrix.name }}.tar            
+      
+#TESTING
+
+      - name: Set enviroment for github-release
+        run: |
+          - name: Save state
+          run: echo "RELEASE_TAG=${{ env.VERSION }}" >> $GITHUB_STATE
+
+          - name: Set output
+          run: echo "RELEASE_NAME={$GITHUB_WORKFLOW}" >> $GITHUB_OUTPUT
+        continue-on-error: true
+      
+      - uses: meeDamian/github-release@2.0
         with:
-          name: Pulsar-${{ env.VERSION }}-${{ matrix.name }}
-          path: |
-            release/pulsard*
-            release/pulsar-qt
-            release/pulsar-qt.exe
-            release/pulsar-cli
-            release/pulsar-cli.exe
-            release/Pulsar-Qt.app
-            
+          token: ${{ secrets.GITHUB_TOKEN }}
+          tag: ${{ env.VERSION }}
+          name: ${{ env.VERSION }}
+          body: >
+            testing.....  
+          gzip: false
+          files: >
+            release-v1.0.0-windows:release/Pulsar-${{ env.VERSION }}-${{ matrix.name }}
+        continue-on-error: true
